### ISSUE TITLE
"Found 43 suspicious words" but no suspicious words remain after filtering - setup issue?

### ISSUE THREAD

**Issue by practicalswift** [seales/spellchecker#2]
Nice project! After seeing the impressive typo fixes in the `scikit-learn` project I wanted to try out `spellchecker` myself but it seems like I'm missing some step in the setup process :-)

This is my test case:

```
$ git clone https://github.com/seales/spellchecker.git
$ cd spellchecker/
$ echo "# thsi fiel contaisn a lto of suspiciosu worsd." > typos.py
$ python spellchecker.py

Enter directory or 'q' to quit. >> /path/to/spellchecker

You entered: '/path/to/spellchecker'

Suspicious Words: 12 --- Files Read: 10 out of 16 --- In 0.05 seconds
Suspicious Words: 22 --- Files Read: 16 out of 16 --- In 0.08 seconds

Found 43 suspicious words. Trying to filter...

Done filtering...

No suspicious words remain.

Enter directory or 'q' to quit. >> q

Exiting now...
```

Should `spellchecker` catch the typos in this test case? Or in other words: what am I doing wrong? :-)

**Comment by seales** [comment]
Thanks for your interest!

I've submitted a patch and your example works now.

**Comment by practicalswift** [comment]
@seales Thank you! Works as expected now :-)
